


#' choose colours
cvi_colours = list(
  cvi_purples = c("#99FFFF","#80CBC4", "#26C6DA","#009999",  "#006064"),
  Three_colors = c("#99FFFF","#33FF99","#006064"),
  Four_colors = c("#99FFFF","#33FF99","#006064","#AD1457"))


#' create a function that generates an actual colour palette from our simple list of colours.

#'@export
#'@param name the name of the colour palette we want to use,
#'@param n variable with number of colours for groups
#'@param cvi_palettes name of my function
#'@all_palettes the list of colour palettes we want to extract our choice from
#'@param type whether we want a discrete or continuous colour palette
cvi_palettes = function(name, n, all_palettes = cvi_colours, type = c("discrete", "continuous")) {
  palette = all_palettes[[name]]
  if (missing(n)) {
    n = length(palette)
  }
  type = match.arg(type)
  out = switch(type,
               continuous = grDevices::colorRampPalette(palette)(n),
               discrete = palette[1:n]
  )
  structure(out, name = name, class = "palette")
}


#we need to make it clear when we are using functions in another package. To do this we can use usethis::use_package().
usethis::use_package("ggplot2")

#Here, we pass our palette colours generated by cvi_palettes() as the values argument in the scale_colour_manual() function from {ggplot2}:
scale_colour_cvi_d = function(name) {
  ggplot2::scale_colour_manual(values = cvi_palettes(name,
                                                     type = "discrete"))
}



#The function to use our colour palettes to change the fill colour is almost identical,
#we simply change the function name, and use scale_fill_manual() instead of scale_colour_manual().

scale_fill_cvi_d = function(name) {
  ggplot2::scale_fill_manual(values = cvi_palettes(name,
                                                   type = "discrete"))
}



#Now for continuous variables.
scale_colour_cvi_c = function(name) {
  ggplot2::scale_colour_gradientn(colours = cvi_palettes(name = name,
                                                         type = "continuous"))
}


scale_fill_cvi_c = function(name) {
  ggplot2::scale_fill_gradientn(colours = cvi_palettes(name = name,
                                                       type = "continuous"))
}


#To ensure that the scale_colour_*() functions work with either the British
#or American spelling of colour, we can simply set one equal to the other:
scale_color_cvi_d = scale_colour_cvi_d
scale_color_cvi_c = scale_colour_cvi_c

